spring:
  application:
    name: "book-service"
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  datasource:
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    url: ${DB_URL}
    driver-class-name: org.postgresql.Driver

    hikari:
      connection-timeout: 60000
      max-lifetime: 180000
      maximum-pool-size: 10
server:
  address: 0.0.0.0
  port: 8081
